AllCops:
  TargetRubyVersion: 2.4


Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 120


Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false


Layout/AlignHash:
  Enabled: false


Naming/PredicateName:
  Enabled: false


Lint/EmptyWhen:
  Enabled: false


Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10
