language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
gemfile:
  - ci/Gemfile-rails-4-2
  - ci/Gemfile-rails-5-0
  - ci/Gemfile-rails-5-1
  - ci/Gemfile-rails-5-2
script:
  - bundle exec rake
  - bundle exec rubocop
before_install:
  - gem update --system
  - gem update bundler
sudo: false
