language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
gemfile:
  - ci/Gemfile-rails-4-1
  - ci/Gemfile-rails-4-2
  - ci/Gemfile-rails-5-0
  - ci/Gemfile-rails-5-1
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: ci/Gemfile-rails-5-1
    - rvm: 2.1.10
      gemfile: ci/Gemfile-rails-5-1
    - rvm: 2.0.0
      gemfile: ci/Gemfile-rails-5-0
    - rvm: 2.1.10
      gemfile: ci/Gemfile-rails-5-0
    - rvm: 2.4.3
      gemfile: ci/Gemfile-rails-4-1
before_install: gem update bundler
sudo: false
